# docker-compose.yml
version: '3.8'
services:
    profilarr:
        image: yourusername/profilarr:latest # For Docker Hub
        container_name: profilarr
        ports:
            - 6868:6868
        volumes:
            - profilarr_data:/config
        environment:
            - TZ=Australia/Adelaide
        env_file:
            - .env
        restart: unless-stopped

volumes:
    profilarr_data:
        name: profilarr_data
